
project_id = "royvktipnkfnpdhytakw"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

# Email testing function
[functions.test-smtp]
verify_jwt = false

# Order email function
[functions.send-order-email]
verify_jwt = false

# Payment callback function for Multicaixa Express
[functions.payment-callback]
verify_jwt = false

# Multicaixa Express callback function
[functions.multicaixa-express-callback]
verify_jwt = false

# Generate EMIS token function
[functions.generate-emis-token]
verify_jwt = false

